### ISSUE TITLE
Configrable values for max blocks being broken on abilities

### ISSUE THREAD

**Issue by RoyalReject** [Direwolf20-MC/JustDireThings#171]
### Describe the feature you'd like to have added

Have a setting/config value for the max_break available to each tier under https://github.com/Direwolf20-MC/JustDireThings/blob/main/src/main/java/com/direwolf20/justdirethings/common/items/interfaces/ToggleableTool.java#L146-L153

**Comment by Direwolf20-MC** [comment]
Done :).  It'll be available in the next update. 

Out of curiosity - do you plan to reduce or increase the defaults? :)

**Comment by RoyalReject** [comment]
Sweet thank you, I plan to increase defaults actually as I was running into issues mainly with the axe and tree felling ability with large spruce trees close to each other. I didn't look into the algorithm used but how it finds branches causes trees one block away although separate would still get caught and cause floating trees as I hit max
